PRELOADED_DECKS = {
    "JEE": [
        # ==========================================
        # PHYSICS - CHAPTER 1: MECHANICS (20 Cards)
        # ==========================================
        {"question": "Physics - Mechanics: State the work-energy theorem.", "answer": "The net work done by all forces acting on a particle equals its change in kinetic energy."},
        {"question": "Physics - Mechanics: Formula for terminal velocity of a sphere dropping in viscous fluid.", "answer": "v = (2r^2 * (rho - sigma) * g) / (9 * eta)"},
        {"question": "Physics - Mechanics: Define conservative forces.", "answer": "Forces where work done depends only on initial and final positions, not on the path taken."},
        {"question": "Physics - Mechanics: State Kepler's third law of planetary motion.", "answer": "The square of the orbital period is proportional to the cube of the semi-major axis: T^2 alpha r^3."},
        {"question": "Physics - Mechanics: Formula for acceleration due to gravity at depth 'd'.", "answer": "g_d = g * (1 - d/R)"},
        {"question": "Physics - Mechanics: What is the velocity of a particle at the highest point of a projectile motion?", "answer": "v = u * cos(theta), directed horizontally."},
        {"question": "Physics - Mechanics: Define the coefficient of restitution (e).", "answer": "e = (Velocity of separation) / (Velocity of approach)"},
        {"question": "Physics - Mechanics: What is the relation between torque and angular momentum?", "answer": "Torque = dL/dt (Rate of change of angular momentum)"},
        {"question": "Physics - Mechanics: State the parallel axes theorem for moment of inertia.", "answer": "I = I_cm + M * d^2"},
        {"question": "Physics - Mechanics: State the perpendicular axes theorem for planar objects.", "answer": "I_z = I_x + I_y"},
        {"question": "Physics - Mechanics: Formula for escape velocity from Earth's surface.", "answer": "v_e = sqrt(2 * G * M / R)"},
        {"question": "Physics - Mechanics: What is the variation of gravity with altitude 'h' (where h << R)?", "answer": "g_h = g * (1 - 2h/R)"},
        {"question": "Physics - Mechanics: Define conservative field condition via potential energy gradient.", "answer": "F = -dU/dr"},
        {"question": "Physics - Mechanics: Time period of a simple pendulum of length L.", "answer": "T = 2 * pi * sqrt(L / g)"},
        {"question": "Physics - Mechanics: Condition for pure rolling of a sphere on a flat surface.", "answer": "v = omega * R and a = alpha * R at the contact point."},
        {"question": "Physics - Mechanics: Work done by a static frictional force during pure rolling?", "answer": "Zero, because instantaneous displacement of the contact point is zero."},
        {"question": "Physics - Mechanics: Express banking angle 'theta' for a frictionless curved road.", "answer": "tan(theta) = v^2 / (r * g)"},
        {"question": "Physics - Mechanics: Center of mass location for a solid hemisphere of radius R.", "answer": "3R / 8 along the axis of symmetry from the base center."},
        {"question": "Physics - Mechanics: Rocket propulsion thrust force formula.", "answer": "Thrust = u * (dm/dt) where u is relative exhaust velocity."},
        {"question": "Physics - Mechanics: What is Hooke's Law within elastic limits?", "answer": "Stress is directly proportional to strain (Stress = Y * Strain)."},

        # ==========================================
        # PHYSICS - CHAPTER 2: ELECTRODYNAMICS (20 Cards)
        # ==========================================
        {"question": "Physics - Electrodynamics: State Gauss's Law in electrostatics.", "answer": "The total electric flux through a closed surface equals net enclosed charge divided by epsilon_0."},
        {"question": "Physics - Electrodynamics: Formula for the capacitance of a parallel plate capacitor.", "answer": "C = (K * epsilon_0 * A) / d"},
        {"question": "Physics - Electrodynamics: Define drift velocity of conduction electrons.", "answer": "The average velocity attained by charged particles due to an electric field: v_d = (e * E * tau) / m."},
        {"question": "Physics - Electrodynamics: State Ampere's Circuital Law.", "answer": "The line integral of magnetic field around any closed loop equals mu_0 * I."},
        {"question": "Physics - Electrodynamics: Write Faraday's Law of electromagnetic induction.", "answer": "The induced electromotive force equals the negative rate of change of magnetic flux: emf = -d(phi)/dt."},
        {"question": "Physics - Electrodynamics: Formula for magnetic field at the center of a circular current loop.", "answer": "B = (mu_0 * I) / (2 * R)"},
        {"question": "Physics - Electrodynamics: State Lenz's Law.", "answer": "The direction of induced current opposes the change in magnetic flux that produced it."},
        {"question": "Physics - Electrodynamics: Energy density stored in an electric field.", "answer": "u_E = 0.5 * epsilon_0 * E^2"},
        {"question": "Physics - Electrodynamics: Energy density stored in a magnetic field.", "answer": "u_B = B^2 / (2 * mu_0)"},
        {"question": "Physics - Electrodynamics: Write the Lorentz force equation.", "answer": "F = q * E + q * (v x B)"},
        {"question": "Physics - Electrodynamics: Self-inductance formula for a long solenoid.", "answer": "L = mu_0 * n^2 * A * l"},
        {"question": "Physics - Electrodynamics: What is the quality factor (Q) of a series LCR circuit?", "answer": "Q = (1 / R) * sqrt(L / C)"},
        {"question": "Physics - Electrodynamics: Resonant frequency formula for a series LCR circuit.", "answer": "f = 1 / (2 * pi * sqrt(L * C))"},
        {"question": "Physics - Electrodynamics: Write Maxwell's displacement current expression.", "answer": "I_d = epsilon_0 * (d(phi_E) / dt)"},
        {"question": "Physics - Electrodynamics: Electric potential at a distance 'r' from a point charge 'q'.", "answer": "V = q / (4 * pi * epsilon_0 * r)"},
        {"question": "Physics - Electrodynamics: State Kirchhoff's current law (KCL).", "answer": "The algebraic sum of currents entering a junction equals zero (Conservation of charge)."},
        {"question": "Physics - Electrodynamics: State Kirchhoff's voltage law (KVL).", "answer": "The algebraic sum of potential changes around any closed loop is zero (Conservation of energy)."},
        {"question": "Physics - Electrodynamics: Torque experienced by an electric dipole in a uniform electric field.", "answer": "Torque = p x E"},
        {"question": "Physics - Electrodynamics: Relation between electric field and potential gradient.", "answer": "E = -dV/dr"},
        {"question": "Physics - Electrodynamics: Force per unit length between two parallel current-carrying wires.", "answer": "F/l = (mu_0 * I_1 * I_2) / (2 * pi * d)"},

        # ==========================================
        # CHEMISTRY - CHAPTER 1: PHYSICAL CHEMISTRY (20 Cards)
        # ==========================================
        {"question": "Chemistry - Physical: What is the hybridisation of Cl in ClO4-?", "answer": "sp3 hybridisation"},
        {"question": "Chemistry - Physical: State Henry's law for solubility of gases.", "answer": "The solubility of a gas in a liquid is directly proportional to its partial pressure: p = K_H * x."},
        {"question": "Chemistry - Physical: Write the integrated rate equation for a first-order reaction.", "answer": "k = (2.303 / t) * log(A_0 / A)"},
        {"question": "Chemistry - Physical: Define conjugate acid-base pairs.", "answer": "Two species that differ only by a single proton (H+ ion)."},
        {"question": "Chemistry - Physical: State the Nernst Equation for cell potentials.", "answer": "E = E_zero - (RT / nF) * ln(Q)"},
        {"question": "Chemistry - Physical: Write the Arrhenius equation for temperature dependence of reaction rates.", "answer": "k = A * e^(-E_a / RT)"},
        {"question": "Chemistry - Physical: State the relationship between cell potential and Gibbs free energy.", "answer": "delta_G = -n * F * E_cell"},
        {"question": "Chemistry - Physical: Define Raoult's Law for volatile liquids.", "answer": "The partial vapor pressure of each component is directly proportional to its mole fraction: p_A = p_A_zero * x_A."},
        {"question": "Chemistry - Physical: Formula for degree of dissociation (alpha) using van 't Hoff factor (i) for dissociation.", "answer": "alpha = (i - 1) / (n - 1)"},
        {"question": "Chemistry - Physical: State Hess's Law of constant heat summation.", "answer": "The total enthalpy change for a chemical reaction is the same regardless of whether it occurs in one step or multiple steps."},
        {"question": "Chemistry - Physical: What is the relation between K_p and K_c?", "answer": "K_p = K_c * (RT)^(delta_n)"},
        {"question": "Chemistry - Physical: Formula for the half-life of a first-order reaction.", "answer": "t_1/2 = 0.693 / k"},
        {"question": "Chemistry - Physical: Define buffer capacity metrics.", "answer": "The number of moles of acid or base added per liter of buffer solution required to change its pH by one unit."},
        {"question": "Chemistry - Physical: State the relationship between solubility product (K_sp) and solubility (S) for a salt like AgCl.", "answer": "K_sp = S^2"},
        {"question": "Chemistry - Physical: What is the packing efficiency of a Face-Centered Cubic (FCC) lattice?", "answer": "74%"},
        {"question": "Chemistry - Physical: What is the packing efficiency of a Body-Centered Cubic (BCC) lattice?", "answer": "68%"},
        {"question": "Chemistry - Physical: Define the Schottky defect in crystals.", "answer": "A stoichiometric defect where stoichiometric numbers of cations and anions are missing from the crystal lattice."},
        {"question": "Chemistry - Physical: Define the Frenkel defect in ionic crystals.", "answer": "A defect where an smaller ion leaves its correct lattice site and occupies an interstitial position."},
        {"question": "Chemistry - Physical: Write down Faraday's First Law of Electrolysis formula.", "answer": "m = Z * I * t"},
        {"question": "Chemistry - Physical: What is the expression for Debye-Huckel Onsager equation for strong electrolytes?", "answer": "Lambda_m = Lambda_m_zero - A * sqrt(C)"},

        # ==========================================
        # CHEMISTRY - CHAPTER 2: ORGANIC CHEMISTRY (20 Cards)
        # ==========================================
        {"question": "Chemistry - Organic: Reagents used in the Hoffmann Bromamide Degradation reaction loop.", "answer": "Br2 mixed alongside sodium hydroxide (NaOH) or KOH aqueous solutions."},
        {"question": "Chemistry - Organic: What is the major product of Williamson Ether synthesis with tert-butyl chloride?", "answer": "Isobutylene (Elimination occurs instead of nucleophilic substitution)."},
        {"question": "Chemistry - Organic: Reagent setup used in Rosenmund Reduction process arrays.", "answer": "H2 over Pd catalyzed alongside BaSO4 deactivated with sulfur poisons."},
        {"question": "Chemistry - Organic: Define anti-Markovnikov addition rule criterion.", "answer": "In presence of peroxides, HBr adds to unsymmetrical alkenes so hydrogen hooks to less-hydrogenated carbon."},
        {"question": "Chemistry - Organic: Identify the product when phenol gets distilled directly over Zinc dust.", "answer": "Benzene"},
        {"question": "Chemistry - Organic: What are the reagents used in Reimer-Tiemann reaction to prepare salicylaldehyde?", "answer": "Chloroform (CHCl3) and aqueous Sodium Hydroxide (NaOH)."},
        {"question": "Chemistry - Organic: What is the intermediate formed during the Reimer-Tiemann reaction?", "answer": "Dichlorocarbene (:CCl2)"},
        {"question": "Chemistry - Organic: Reagents used in the Clemmensen Reduction.", "answer": "Zinc amalgam (Zn/Hg) and concentrated Hydrochloric Acid (HCl)."},
        {"question": "Chemistry - Organic: Reagents used in Wolff-Kishner Reduction loops.", "answer": "Hydrazine (NH2NH2) followed by heating with KOH in ethylene glycol."},
        {"question": "Chemistry - Organic: What test distinguishes Aldehydes from Ketones using ammoniacal silver nitrate?", "answer": "Tollens' Test (Forms a shiny silver mirror)."},
        {"question": "Chemistry - Organic: Condition required for a molecule to undergo Cannizzaro reaction.", "answer": "Aldehydes lacking an alpha-hydrogen atom (e.g., Formaldehyde, Benzaldehyde)."},
        {"question": "Chemistry - Organic: What is the electrophile in aromatic nitration?", "answer": "Nitronium ion (NO2+)"},
        {"question": "Chemistry - Organic: What product is formed when primary amine reacts with Chloroform and KOH?", "answer": "Isocyanide or Carbylamine (foul-smelling compound)."},
        {"question": "Chemistry - Organic: What is Hinsberg's reagent chemically?", "answer": "Benzenesulfonyl chloride (C6H5SO2Cl)."},
        {"question": "Chemistry - Organic: Which mechanism does the substitution of primary alkyl halides generally follow?", "answer": "SN2 mechanism (Bi-molecular nucleophilic substitution)."},
        {"question": "Chemistry - Organic: Which intermediate is formed in an SN1 reaction pathway?", "answer": "A planar, stable carbocation intermediate."},
        {"question": "Chemistry - Organic: State Huckel's rule of aromaticity.", "answer": "The planar cyclic conjugated ring system must possess (4n + 2) pi electrons."},
        {"question": "Chemistry - Organic: What reagent is used in Kolbe's reaction to form Salicylic acid from Phenol?", "answer": "Carbon dioxide (CO2) followed by acidification."},
        {"question": "Chemistry - Organic: What compound is known as Lucas reagent?", "answer": "Anhydrous Zinc Chloride (ZnCl2) in concentrated HCl."},
        {"question": "Chemistry - Organic: Major product obtained when HBr adds to propene via Markovnikov rule.", "answer": "2-Bromopropane"},

        # ==========================================
        # MATHS - CHAPTER 1: CALCULUS (20 Cards)
        # ==========================================
        {"question": "Maths - Calculus: State the conditions required for Rolle's Theorem on interval [a,b].", "answer": f"f(x) must be continuous on [a,b], differentiable on open (a,b), and f(a) = f(b)."},
        {"question": "Maths - Calculus: Evaluate value of Integral dx/(1+x^2) bounded from 0 to 1.", "answer": "pi / 4"},
        {"question": "Maths - Calculus: State Leibniz's rule for differentiating under integral signs.", "answer": "d/dx [int_{u(x)}^{v(x)} f(t)dt] = f(v(x))*v'(x) - f(u(x))*u'(x)"},
        {"question": "Maths - Calculus: Write the general solution format for linear differential equation: dy/dx + Py = Q.", "answer": "y * e^(int P dx) = int (Q * e^(int P dx)) dx + C"},
        {"question": "Maths - Calculus: Condition for two functional curves to cut orthogonally at intersections.", "answer": "The product of their tangent gradients at the intersection point must equal negative unity (m_1 * m_2 = -1)."},
        {"question": "Maths - Calculus: Formula for standard limit of (sin x) / x as x approaches 0.", "answer": "1"},
        {"question": "Maths - Calculus: Write the expansion of e^x series.", "answer": "1 + x + x^2/2! + x^3/3! + ..."},
        {"question": "Maths - Calculus: State L'Hopital's Rule condition.", "answer": "If a limit evaluates to 0/0 or inf/inf, it can be evaluated by differentiating numerator and denominator independently."},
        {"question": "Maths - Calculus: Integral of ln(x) dx.", "answer": "x * ln(x) - x + C"},
        {"question": "Maths - Calculus: State Lagrange's Mean Value Theorem expression.", "answer": "f'(c) = (f(b) - f(a)) / (b - a) for some c in open (a,b)."},
        {"question": "Maths - Calculus: Condition for a function to be strictly increasing on an interval.", "answer": "f'(x) > 0 for all x in that interval."},
        {"question": "Maths - Calculus: Point of inflection condition inside higher derivatives.", "answer": "f''(x) = 0 and f'''(x) != 0 at that specific location."},
        {"question": "Maths - Calculus: State the property of definite integrals for int_{-a}^{a} f(x) dx when f(x) is odd.", "answer": "Zero"},
        {"question": "Maths - Calculus: State the property of definite integrals for int_{0}^{a} f(x) dx.", "answer": "Equal to int_{0}^{a} f(a - x) dx"},
        {"question": "Maths - Calculus: What is the integrating factor (IF) for dy/dx + Py = Q?", "answer": "IF = e^(int P dx)"},
        {"question": "Maths - Calculus: Write down the derivative of a^x with respect to x.", "answer": "a^x * ln(a)"},
        {"question": "Maths - Calculus: Formula for curvature radius radius baseline calculation.", "answer": "R = [1 + (dy/dx)^2]^(3/2) / |d^2y/dx^2|"},
        {"question": "Maths - Calculus: Integral of sec(x) dx.", "answer": "ln|sec(x) + tan(x)| + C"},
        {"question": "Maths - Calculus: Condition for continuity of f(x) at x = a.", "answer": "Left-hand limit = Right-hand limit = Functional value f(a)."},
        {"question": "Maths - Calculus: Express Taylor series expansion format around point a.", "answer": "f(x) = f(a) + f'(a)(x-a) + f''(a)(x-a)^2/2! + ..."},

        # ==========================================
        # MATHS - CHAPTER 2: COORDINATE GEOMETRY (20 Cards)
        # ==========================================
        {"question": "Maths - Coordinate Geometry: General equation of a tangent to parabola y^2 = 4ax with gradient 'm'.", "answer": "y = mx + a/m"},
        {"question": "Maths - Coordinate Geometry: Condition for line y = mx + c to touch ellipse x^2/a^2 + y^2/b^2 = 1.", "answer": "c^2 = a^2 * m^2 + b^2"},
        {"question": "Maths - Coordinate Geometry: Formula for the length of perpendicular from (x_1, y_1) to Ax + By + C = 0.", "answer": "d = |Ax_1 + By_1 + C| / sqrt(A^2 + B^2)"},
        {"question": "Maths - Coordinate Geometry: Eccentricity relation equation for a hyperbola.", "answer": "e = sqrt(1 + b^2 / a^2)"},
        {"question": "Maths - Coordinate Geometry: Co-ordinates of the centroid of a triangle with vertices (x_i, y_i).", "answer": "((x_1+x_2+x_3)/3, (y_1+y_2+y_3)/3)"},
        {"question": "Maths - Coordinate Geometry: Focus coordinates for the parabola x^2 = -4ay.", "answer": "(0, -a)"},
        {"question": "Maths - Coordinate Geometry: Directrix equation for the parabola y^2 = 4ax.", "answer": "x = -a"},
        {"question": "Maths - Coordinate Geometry: Length of the latus rectum of ellipse x^2/a^2 + y^2/b^2 = 1 (where a > b).", "answer": "2b^2 / a"},
        {"question": "Maths - Coordinate Geometry: Distance between the foci of an ellipse.", "answer": "2ae"},
        {"question": "Maths - Coordinate Geometry: Distance between directrices of a hyperbola.", "answer": "2a / e"},
        {"question": "Maths - Coordinate Geometry: Parametric coordinates of any point on the ellipse x^2/a^2 + y^2/b^2 = 1.", "answer": "(a*cos(theta), b*sin(theta))"},
        {"question": "Maths - Coordinate Geometry: Angle between two intersecting lines with gradients m_1 and m_2.", "answer": "tan(theta) = |(m_1 - m_2) / (1 + m_1*m_2)|"},
        {"question": "Maths - Coordinate Geometry: General equation of a circle passing through origin with intercepts a and b.", "answer": "x^2 + y^2 - ax - by = 0"},
        {"question": "Maths - Coordinate Geometry: Condition for orthogonally intersecting circles x^2+y^2+2g_i x+2f_i y+c_i=0.", "answer": "2*g_1*g_2 + 2*f_1*f_2 = c_1 + c_2"},
        {"question": "Maths - Coordinate Geometry: Equation of Director Circle for ellipse x^2/a^2 + y^2/b^2 = 1.", "answer": "x^2 + y^2 = a^2 + b^2"},
        {"question": "Maths - Coordinate Geometry: Asymptotes equations for hyperbola x^2/a^2 - y^2/b^2 = 1.", "answer": "y = +/- (b/a) * x"},
        {"question": "Maths - Coordinate Geometry: Condition for lines Ax+By+C=0 and A'x+B'x+C'=0 to match parallel alignments.", "answer": "A/A' = B/B'"},
        {"question": "Maths - Coordinate Geometry: Area of a triangle using vertex coordinates matrix.", "answer": "Area = 0.5 * |x_1(y_2-y_3) + x_2(y_3-y_1) + x_3(y_1-y_2)|"},
        {"question": "Maths - Coordinate Geometry: Equation of chord of contact from external point (x_1, y_1) to circle x^2+y^2=r^2.", "answer": "x*x_1 + y*y_1 = r^2"},
        {"question": "Maths - Coordinate Geometry: Length of tangent from external point (x_1, y_1) to circle x^2+y^2+2gx+2fy+c=0.", "answer": "L = sqrt(x_1^2 + y_1^2 + 2gx_1 + 2fy_1 + c)"}
    ],
    "NEET": [
        # ==========================================
        # BIOLOGY - CHAPTER 1: BOTANY (20 Cards)
        # ==========================================
        {"question": "Biology - Botany: Where exactly does the Krebs cycle take place in eukaryotic cellular geometry?", "answer": "Within the internal mitochondrial matrix space."},
        {"question": "Biology - Botany: Which hormone promotes apical dominance in plants?", "answer": "Auxin (Indole-3-acetic acid)."},
        {"question": "Biology - Botany: Name the primary CO2 acceptor molecule in C4 photosynthetic cycles.", "answer": "Phosphoenolpyruvate (PEP)."},
        {"question": "Biology - Botany: State the function of tapetum layer within microsporangium configurations.", "answer": "Provides structural nourishment to developing pollen grain cells."},
        {"question": "Biology - Botany: Define parthenocarpy with commercial crop examples.", "answer": "Development of seedless fruits without fertilization processes (e.g., Banana)."},
        {"question": "Biology - Botany: What are the criteria for essentiality of elements in plant nutrition?", "answer": "Element must be indispensable for growth, irreplaceable by others, and directly involved in metabolism."},
        {"question": "Biology - Botany: Name the fungus that produces Cyclosporin A immunosuppressants.", "answer": "Trichoderma polysporum."},
        {"question": "Biology - Botany: Which ecological pyramid format cannot execute inverted positions?", "answer": "Pyramid of Energy is always upright due to thermodynamic transfer rules."},
        {"question": "Biology - Botany: Define endospermic seeds with crop instances.", "answer": "Seeds retaining endosperm tissue upon reaching maturity stages (e.g., Maize, Castor, Wheat)."},
        {"question": "Biology - Botany: What is the genetic ploidy level of endosperm tissue in Angiosperms?", "answer": "Triploid (3n) due to triple fusion events."},
        {"question": "Biology - Botany: Which tracking pigment captures solar energy during oxygenic photosynthesis?", "answer": "Chlorophyll-a molecules."},
        {"question": "Biology - Botany: Name the enzyme complex cataloging nitrogen fixation within root nodules.", "answer": "Nitrogenase enzyme complex (highly sensitive to molecular oxygen)."},
        {"question": "Biology - Botany: What unique anatomical structural configuration defines leaves of C4 plants?", "answer": "Kranz Anatomy layout configuration."},
        {"question": "Biology - Botany: Which gaseous plant growth regulator triggers quick ripening of fruit?", "answer": "Ethylene"},
        {"question": "Biology - Botany: Name the structural tissue transport channel that shifts sugars through plant bodies.", "answer": "Phloem sieve tube networks."},
        {"question": "Biology - Botany: Define the biological term for the cell wall splitting step during cellular divisions.", "answer": "Cytokinesis process loop."},
        {"question": "Biology - Botany: What specialized pore configurations handle guttation drops along leaf borders?", "answer": "Hydathodes structures."},
        {"question": "Biology - Botany: Name the botanical family grouping holding tomato and potato plants.", "answer": "Solanaceae family classification."},
        {"question": "Biology - Botany: Define thematic photoperiodism behavior responses.", "answer": "Physiological responses of plants relative to the comparative duration of daily light and dark cycles."},
        {"question": "Biology - Botany: Which phase profile captures DNA replication during standard interphase blocks?", "answer": "S-phase (Synthesis Phase)."},

        # ==========================================
        # BIOLOGY - CHAPTER 2: ZOOLOGY (20 Cards)
        # ==========================================
        {"question": "Biology - Zoology: What is the primary physiological function of interstitial Leydig cells?", "answer": "Synthesis and secretion of testicular androgen hormones (testosterone)."},
        {"question": "Biology - Zoology: Which specific adenohypophyseal hormone triggers immediate ovulation cycles?", "answer": "Luteinizing Hormone (LH surge)."},
        {"question": "Biology - Zoology: Name the structural and functional unit of the human kidney network.", "answer": "Nephron"},
        {"question": "Biology - Zoology: Where are the bundle of His muscle fibers localized inside human cardiovascular networks?", "answer": "Interventricular septal walls of heart systems."},
        {"question": "Biology - Zoology: Name the structural cell types secreting Pepsinogen zymogens inside gastric pits.", "answer": "Chief cells (Peptic cells)."},
        {"question": "Biology - Zoology: State the exact genetic transmission mutation pattern defining Sickle Cell Anemia tracks.", "answer": "Autosomal recessive point mutation changing Glutamic acid to Valine at 6th slot of beta-globin chain."},
        {"question": "Biology - Zoology: Which antibody class shows elevated counts during acute hypersensitivity or allergic responses?", "answer": "Immunoglobulin E (IgE)."},
        {"question": "Biology - Zoology: What parameter describes the human structural joint linking atlas and axis vertebrae?", "answer": "Pivot joint layout configuration."},
        {"question": "Biology - Zoology: Name the site where primary spermatogenesis transformations happen structurally.", "answer": "Seminiferous tubules within testicular configurations."},
        {"question": "Biology - Zoology: Which hormone lowers human blood calcium profiles when hypercalcemia patterns develop?", "answer": "Thyrocalcitonin (TCT) secreted by parafollicular C-cells."},
        {"question": "Biology - Zoology: Name the primary phagocytic leukocyte configurations shielding human immune networks.", "answer": "Neutrophils and Monocytes."},
        {"question": "Biology - Zoology: Where are structural matching audio receptors localized within human ear apparatus systems?", "answer": "Organ of Corti positioned over basilar membrane regions."},
        {"question": "Biology - Zoology: Name the primary structural connective link tying muscle blocks to skeletal layouts.", "answer": "Tendons"},
        {"question": "Biology - Zoology: Which endocrine entity releases melatonin into human systemic loops?", "answer": "Pineal gland structures."},
        {"question": "Biology - Zoology: What unique breathing organ configuration handles ventilation for insects?", "answer": "Tracheolar tube infrastructure networks."},
        {"question": "Biology - Zoology: Name the primary target bile component formatting lipid emulsions.", "answer": "Bile salts (Sodium glycocholate and taurocholate)."},
        {"question": "Biology - Zoology: Which cell structure component isolates the standard blood-filtering slit interface inside Bowman capsules?", "answer": "Podocytes"},
        {"question": "Biology - Zoology: Define the physiological function of surfactant lining pulmonary alveoli interfaces.", "answer": "Lowers internal surface tension to guard alveolar walls against collapse loops."},
        {"question": "Biology - Zoology: Name the primary oxygen-carrying metalloprotein layout formatting red blood cell masses.", "answer": "Hemoglobin"},
        {"question": "Biology - Zoology: Which neural center guides automatic autonomic respiratory cycle parameters natively?", "answer": "Medulla Oblongata center clusters."}
    ],
    "CAT": [
        # ==========================================
        # QUANT - CHAPTER 1: ARITHMETIC (20 Cards)
        # ==========================================
        {"question": "Quant - Arithmetic: Define the allegation rule formula ratio relationship.", "answer": "Cheaper Quantity / Dearer Quantity = (Dearer Price - Mean Price) / (Mean Price - Cheaper Price)"},
        {"question": "Quant - Arithmetic: Formula for effective compound interest rate when compounding occurs half-yearly.", "answer": "R_eff = (1 + R / 200)^2 - 1"},
        {"question": "Quant - Arithmetic: If speed ratios scale as a:b, what is the corresponding travel duration ratio?", "answer": "b : a (inverse variance tracking properties)"},
        {"question": "Quant - Arithmetic: Work efficiency rule expression relating men, days, and output volume metric variables.", "answer": "(M_1 * D_1 * H_1) / W_1 = (M_2 * D_2 * H_2) / W_2"},
        {"question": "Quant - Arithmetic: Express relationship between LCM, HCF, and product limits of two numbers A and B.", "answer": "LCM(A,B) * HCF(A,B) = A * B"},
        {"question": "Quant - Arithmetic: Two values fluctuate as 20% growth and 20% decay. Express net percentage variance.", "answer": "Net 4% drop down across final values."},
        {"question": "Quant - Arithmetic: Formula for calculating a discount sequence of x% followed by y%.", "answer": "Net Discount = (x + y - (x * y / 100))%"},
        {"question": "Quant - Arithmetic: Express relative velocity computation when two objects speed along matching tracks.", "answer": "Relative speed = |V_1 - V_2|"},
        {"question": "Quant - Arithmetic: Express relative velocity computation when two objects run opposite directions.", "answer": "Relative speed = V_1 + V_2"},
        {"question": "Quant - Arithmetic: Express relationship defining average speed mapping across matching distance slots.", "answer": "Average Speed = (2 * v_1 * v_2) / (v_1 + v_2)"},
        {"question": "Quant - Arithmetic: Formula for finding simple interest accumulation values.", "answer": "SI = (P * R * T) / 100"},
        {"question": "Quant - Arithmetic: Express final compounding balance equation formula parameters.", "answer": "A = P * (1 + R/100)^T"},
        {"question": "Quant - Arithmetic: Difference between CI and SI for 2 years duration constants.", "answer": "Difference = P * (R / 100)^2"},
        {"question": "Quant - Arithmetic: Difference between CI and SI for 3 years duration constants.", "answer": "Difference = P * (R / 100)^2 * (3 + R / 100)"},
        {"question": "Quant - Arithmetic: Rule configuration defining profit percentages over cost baseline variables.", "answer": "Profit % = ((Selling Price - Cost Price) / Cost Price) * 100"},
        {"question": "Quant - Arithmetic: Rule configuration defining loss percentages over cost baseline variables.", "answer": "Loss % = ((Cost Price - Selling Price) / Cost Price) * 100"},
        {"question": "Quant - Arithmetic: What does a partnership configuration map if capital timelines vary?", "answer": "Profit split scales according to the product of investment capital and active timeline allocation: C_1*T_1 : C_2*T_2."},
        {"question": "Quant - Arithmetic: Express net downstream vector velocity relating boat speed B and stream flow S.", "answer": "Downstream speed = B + S"},
        {"question": "Quant - Arithmetic: Express net upstream vector velocity relating boat speed B and stream flow S.", "answer": "Upstream speed = B - S"},
        {"question": "Quant - Arithmetic: If a pipe fills tank surfaces over X hours, what fraction loads inside one hour?", "answer": "1 / X total volume share capacity metrics."},

        # ==========================================
        # QUANT - CHAPTER 2: ALGEBRA (20 Cards)
        # ==========================================
        {"question": "Quant - Algebra: What is the combinations equation to distribute n items containing p identical entities?", "answer": "Total paths = n! / p!"},
        {"question": "Quant - Algebra: Solve for base element x constraints if: log_2(x) + log_4(x) = 6.", "answer": "Calculated value x = 16"},
        {"question": "Quant - Algebra: Condition for a quadratic expression ax^2 + bx + c to be always positive for all real x.", "answer": "a > 0 and discriminant D < 0 (b^2 - 4ac < 0)"},
        {"question": "Quant - Algebra: Sum of an infinite geometric progression sequence configuration constraint.", "answer": "S_inf = a / (1 - r) provided absolute ratio bounds stay beneath unity (|r| < 1)."},
        {"question": "Quant - Algebra: State the relationship between Arithmetic Mean (AM) and Geometric Mean (GM).", "answer": "AM >= GM for all positive real numbers."},
        {"question": "Quant - Algebra: Find product values tracking all roots inside quadratic ax^2 + bx + c = 0.", "answer": "Product = c / a"},
        {"question": "Quant - Algebra: Find sum values tracking all roots inside quadratic ax^2 + bx + c = 0.", "answer": "Sum = -b / a"},
        {"question": "Quant - Algebra: Express sum equation formatting across n values inside arithmetic sequences.", "answer": "S_n = (n / 2) * [2a + (n - 1)d]"},
        {"question": "Quant - Algebra: Express value mapping calculation for the n-th slot inside geometric progressions.", "answer": "T_n = a * r^(n - 1)"},
        {"question": "Quant - Algebra: Sum of the first 'n' natural numbers formula expression.", "answer": "S = [n * (n + 1)] / 2"},
        {"question": "Quant - Algebra: Sum of cubes of the first 'n' natural numbers formula expression.", "answer": "S = [n * (n + 1) / 2]^2"},
        {"question": "Quant - Algebra: Express baseline condition generating equal roots across quadratic parameters.", "answer": "Discriminant equals zero (b^2 - 4ac = 0)."},
        {"question": "Quant - Algebra: Express baseline condition generating imaginary roots across quadratic parameters.", "answer": "Discriminant drops below zero (b^2 - 4ac < 0)."},
        {"question": "Quant - Algebra: Logarithmic base change rule transformation statement identity.", "answer": "log_a(b) = log_c(b) / log_c(a)"},
        {"question": "Quant - Algebra: Number of terms inside full multinomial expansions mapping (x + y)^n layouts.", "answer": "n + 1 distinct terms."},
        {"question": "Quant - Algebra: Write the identity mapping expansion format for a^3 - b^3.", "answer": "(a - b) * (a^2 + ab + b^2)"},
        {"question": "Quant - Algebra: Express geometric mean computation across two metrics A and B.", "answer": "GM = sqrt(A * B)"},
        {"question": "Quant - Algebra: Express harmonic mean computation across two metrics A and B.", "answer": "HM = (2 * A * B) / (A + B)"},
        {"question": "Quant - Algebra: Maximum value of product X * Y when their sum X + Y is a constant C.", "answer": "Occurs when X = Y = C / 2."},
        {"question": "Quant - Algebra: Express linear solution behavior if system profiles show: a_1/a_2 == b_1/b_2 != c_1/c_2.", "answer": "The system represents parallel lines and contains zero valid solutions."}
    ]
}